export default {
  HOME: "/",
  MEN: "/product/men",
  WOMEN: "/product/women",
  CHECKOUT: "/checkout",
  CHECKOUT_SHIPPING: "/checkout/shipping",
  CHECKOUT_PAYMENT: "/checkout/payment",
  CHECKOUT_REVIEW: "/checkout/review",
  CHECKOUT_AUTH: "/checkout/auth",
  CART: "/cart",
  MY_PROFILE: "/me",
  MY_ORDERS: "/me/orders",
  MY_WISHLIST: "/me/wishlist",
  PRODUCT: (id: string) => ({ href: "/product/[id]", as: `/product/${id}` }),
};
